### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by ondrejsevcik** [nucleartide/ember-elm#27]
Hi, when I run `ember test` I get following error

```
Uncaught Error: Could not find module `ember` imported from `ember-resolver/resolver` at http://localhost:7357/assets/vendor.js, line 256\n'
    ...
not ok 2 Chrome 69.0 - Global error: Uncaught Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 24541
```

I'm using Mac & Chrome.
```
ember-cli: 2.11.0-beta.1
node: 6.0.0
os: darwin x64
```

Is it just me or are tests currently broken?

**Comment by ondrejsevcik** [comment]
Well actually not just tests, but also the app is broken for me. Not sure what exactly is causing this issue yet. 

![image](https://user-images.githubusercontent.com/4136929/45965617-3fb7c380-c029-11e8-98dc-40d94a2bbe43.png)

**Comment by MattCheely** [comment]
I also noticed this. I am hoping to resolve it as part of the updates for #22, which I started on a few weeks ago, but I haven't had the chance to work on it in a while.
